<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-DataLake.BatchProcessor-718755c2-39c0-4b29-8578-81bd998f7702</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MediatR" Version="12.4.1" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
    <PackageReference Include="Serilog.Extensions.Hosting" Version="8.0.0" />
    <PackageReference Include="Serilog.Settings.Configuration" Version="8.0.4" />
    <PackageReference Include="Serilog.Sinks.Console" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DataLake.Domain\DataLake.Domain.csproj" />
    <ProjectReference Include="..\DataLake.Application\DataLake.Application.csproj" />
    <ProjectReference Include="..\DataLake.Infrastructure\DataLake.Infrastructure.csproj" />
  </ItemGroup>
</Project>
